#!/bin/sh

function git-prompt-info() {
    local branch=""
    branch=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
    local git_status=$(git status --porcelain 2>/dev/null)
    local color=green
    if echo "$git_status" | grep -q "^ M"; then
        color=yellow
        branch="${branch}*"
    fi
    if echo "$git_status" | grep -qE "^ A|^\?\?"; then
        color=yellow
        branch="${branch}+"
    fi
    if echo "$git_status" | grep -q "^ D"; then
        color=yellow
        branch="${branch}-"
    fi
    if [[ -n "$branch" ]]; then
        if [ ${#branch} -gt 20 ]; then
            branch="${branch:0:17}..."
        fi
        branch=" [%F{${color}}${branch}%F{reset}]"
    fi
    echo "$branch"
}
